services:
  app:
    build: .
    ports: ["3000:3000"]
    volumes: [".:/app"]
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    depends_on: [db]
  db:
    image: postgres:16
    platform: linux/amd64
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports: ["5432:5432"]