CREATE TABLE "Usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(255) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "senha" varchar(255) NOT NULL,
  "nivel" varchar(50) DEFAULT 'padrao'
);

CREATE TABLE "Filme" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" varchar(255) NOT NULL,
  "diretor" varchar(255),
  "ano" int,
  "sinopse" text
);

CREATE TABLE "Review" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conteudo_texto" text NOT NULL,
  "nota" int,
  "usuario_id" int NOT NULL,
  "filme_id" int NOT NULL,
  "data_criacao" timestamp
);

ALTER TABLE "Review" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuario" ("id");

ALTER TABLE "Review" ADD FOREIGN KEY ("filme_id") REFERENCES "Filme" ("id");
